// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.ClearSecretRequest} request
 * @returns {$CancellablePromise<$models.SecretActionResult>}
 */
export function ClearSecret(request) {
    return $Call.ByID(335200739, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.SaveSecretRequest} request
 * @returns {$CancellablePromise<$models.SecretActionResult>}
 */
export function SaveSecret(request) {
    return $Call.ByID(2795356703, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SecretStatus>}
 */
export function Status() {
    return $Call.ByID(892689924).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SecretActionResult.createFrom;
const $$createType1 = $models.SecretStatus.createFrom;
