// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ApplyPreview {
    /**
     * Creates a new ApplyPreview instance.
     * @param {Partial<ApplyPreview>} [$$source = {}] - The source object to create the ApplyPreview.
     */
    constructor($$source = {}) {
        if (!("hostsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostsPath"] = "";
        }
        if (!("lineCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lineCount"] = 0;
        }
        if (!("addedLines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["addedLines"] = 0;
        }
        if (!("removedLines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removedLines"] = 0;
        }
        if (!("changed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["changed"] = false;
        }
        if (!("enabledProfiles" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["enabledProfiles"] = [];
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {Conflict[]}
             */
            this["conflicts"] = [];
        }
        if (!("currentContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentContent"] = "";
        }
        if (!("finalContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["finalContent"] = "";
        }
        if (!("diffText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["diffText"] = "";
        }
        if (!("requiresConfirm" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresConfirm"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastPreviewError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplyPreview}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enabledProfiles" in $$parsedSource) {
            $$parsedSource["enabledProfiles"] = $$createField5_0($$parsedSource["enabledProfiles"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField6_0($$parsedSource["conflicts"]);
        }
        return new ApplyPreview(/** @type {Partial<ApplyPreview>} */($$parsedSource));
    }
}

export class ApplyResult {
    /**
     * Creates a new ApplyResult instance.
     * @param {Partial<ApplyResult>} [$$source = {}] - The source object to create the ApplyResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("requiresConfirm" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresConfirm"] = false;
        }
        if (!("preview" in $$source)) {
            /**
             * @member
             * @type {ApplyPreview}
             */
            this["preview"] = (new ApplyPreview());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastApplyError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["confirmationCommand"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplyResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField3_0($$parsedSource["preview"]);
        }
        return new ApplyResult(/** @type {Partial<ApplyResult>} */($$parsedSource));
    }
}

export class Conflict {
    /**
     * Creates a new Conflict instance.
     * @param {Partial<Conflict>} [$$source = {}] - The source object to create the Conflict.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("ips" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ips"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Conflict}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ips" in $$parsedSource) {
            $$parsedSource["ips"] = $$createField1_0($$parsedSource["ips"]);
        }
        return new Conflict(/** @type {Partial<Conflict>} */($$parsedSource));
    }
}

export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["system"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (!("hostsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostsPath"] = "";
        }
        if (!("legacyPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["legacyPath"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("enabledCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["enabledCount"] = 0;
        }
        if (!("systemReadable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["systemReadable"] = false;
        }
        if (!("systemBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["systemBytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSaveError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastReadError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastApplyError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastRemoteError"] = undefined;
        }
        if (!("legacyImported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["legacyImported"] = false;
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {Profile[]}
             */
            this["profiles"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["virtualizedPath"] = undefined;
        }
        if (!("virtualizedExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["virtualizedExists"] = false;
        }
        if (!("virtualizedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["virtualizedBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField12_0($$parsedSource["profiles"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Conflict.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ApplyPreview.createFrom;
const $$createType4 = Profile.createFrom;
const $$createType5 = $Create.Array($$createType4);
