// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {boolean} confirmed
 * @returns {$CancellablePromise<$models.ApplyResult>}
 */
export function ApplyEnabledProfiles(confirmed) {
    return $Call.ByID(2761156011, confirmed).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function FetchRemote(id) {
    return $Call.ByID(3174365898, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Profile[]>}
 */
export function List() {
    return $Call.ByID(2615945724).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function NewProfile() {
    return $Call.ByID(581025743).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ApplyPreview>}
 */
export function PreviewApply() {
    return $Call.ByID(821861924).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Remove(id) {
    return $Call.ByID(2900541700, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.Status>}
 */
export function SetEnabled(id, enabled) {
    return $Call.ByID(1825250861, id, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(1001960830).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.Profile} next
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Upsert(next) {
    return $Call.ByID(3334111175, next).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ApplyResult.createFrom;
const $$createType1 = $models.Status.createFrom;
const $$createType2 = $models.Profile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ApplyPreview.createFrom;
