// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Capability {
    /**
     * Creates a new Capability instance.
     * @param {Partial<Capability>} [$$source = {}] - The source object to create the Capability.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capability instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Capability}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capability(/** @type {Partial<Capability>} */($$parsedSource));
    }
}

export class DiagnosticsExportResult {
    /**
     * Creates a new DiagnosticsExportResult instance.
     * @param {Partial<DiagnosticsExportResult>} [$$source = {}] - The source object to create the DiagnosticsExportResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["createdAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["included"] = undefined;
        }
        if (!("logIncluded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["logIncluded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsExportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticsExportResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("included" in $$parsedSource) {
            $$parsedSource["included"] = $$createField5_0($$parsedSource["included"]);
        }
        return new DiagnosticsExportResult(/** @type {Partial<DiagnosticsExportResult>} */($$parsedSource));
    }
}

export class EnvironmentStatus {
    /**
     * Creates a new EnvironmentStatus instance.
     * @param {Partial<EnvironmentStatus>} [$$source = {}] - The source object to create the EnvironmentStatus.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("legacyName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["legacyName"] = "";
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {Capability[]}
             */
            this["capabilities"] = [];
        }
        if (!("diagnostics" in $$source)) {
            /**
             * @member
             * @type {RuntimeDiagnostics}
             */
            this["diagnostics"] = (new RuntimeDiagnostics());
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {ShellStatus}
             */
            this["shell"] = (new ShellStatus());
        }
        if (!("legacyRuntime" in $$source)) {
            /**
             * @member
             * @type {LegacyRuntimeStatus}
             */
            this["legacyRuntime"] = (new LegacyRuntimeStatus());
        }
        if (!("searchPerformance" in $$source)) {
            /**
             * @member
             * @type {SearchPerformanceStatus}
             */
            this["searchPerformance"] = (new SearchPerformanceStatus());
        }
        if (!("fileSearch" in $$source)) {
            /**
             * @member
             * @type {FileSearchStatus}
             */
            this["fileSearch"] = (new FileSearchStatus());
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {LogStatus}
             */
            this["logs"] = (new LogStatus());
        }
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {RuntimeMetric[]}
             */
            this["metrics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentStatus}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField2_0($$parsedSource["capabilities"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField3_0($$parsedSource["diagnostics"]);
        }
        if ("shell" in $$parsedSource) {
            $$parsedSource["shell"] = $$createField4_0($$parsedSource["shell"]);
        }
        if ("legacyRuntime" in $$parsedSource) {
            $$parsedSource["legacyRuntime"] = $$createField5_0($$parsedSource["legacyRuntime"]);
        }
        if ("searchPerformance" in $$parsedSource) {
            $$parsedSource["searchPerformance"] = $$createField6_0($$parsedSource["searchPerformance"]);
        }
        if ("fileSearch" in $$parsedSource) {
            $$parsedSource["fileSearch"] = $$createField7_0($$parsedSource["fileSearch"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField8_0($$parsedSource["logs"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField9_0($$parsedSource["metrics"]);
        }
        return new EnvironmentStatus(/** @type {Partial<EnvironmentStatus>} */($$parsedSource));
    }
}

export class FileSearchStatus {
    /**
     * Creates a new FileSearchStatus instance.
     * @param {Partial<FileSearchStatus>} [$$source = {}] - The source object to create the FileSearchStatus.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dllPath"] = undefined;
        }
        if (!("dllFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dllFound"] = false;
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceName"] = undefined;
        }
        if (!("serviceInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["serviceInstalled"] = false;
        }
        if (!("serviceRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["serviceRunning"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceState"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serviceError"] = undefined;
        }
        if (!("indexing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["indexing"] = false;
        }
        if (!("indexedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexedCount"] = 0;
        }
        if (!("volumeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["volumeCount"] = 0;
        }
        if (!("requiresAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresAdmin"] = false;
        }
        if (!("elevated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["elevated"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["indexStartedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["indexFinishedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastQuery"] = undefined;
        }
        if (!("lastElapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastElapsedMs"] = 0;
        }
        if (!("lastResultCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastResultCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastUpdatedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["coverageHint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["policyErrors"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSearchStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileSearchStatus}
     */
    static createFrom($$source = {}) {
        const $$createField22_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policyErrors" in $$parsedSource) {
            $$parsedSource["policyErrors"] = $$createField22_0($$parsedSource["policyErrors"]);
        }
        return new FileSearchStatus(/** @type {Partial<FileSearchStatus>} */($$parsedSource));
    }
}

export class LegacyHandoffRequest {
    /**
     * Creates a new LegacyHandoffRequest instance.
     * @param {Partial<LegacyHandoffRequest>} [$$source = {}] - The source object to create the LegacyHandoffRequest.
     */
    constructor($$source = {}) {
        if (!("confirm" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirm"] = false;
        }
        if (!("force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["timeoutMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LegacyHandoffRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LegacyHandoffRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LegacyHandoffRequest(/** @type {Partial<LegacyHandoffRequest>} */($$parsedSource));
    }
}

export class LegacyHandoffResult {
    /**
     * Creates a new LegacyHandoffResult instance.
     * @param {Partial<LegacyHandoffResult>} [$$source = {}] - The source object to create the LegacyHandoffResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("before" in $$source)) {
            /**
             * @member
             * @type {LegacyRuntimeStatus}
             */
            this["before"] = (new LegacyRuntimeStatus());
        }
        if (!("after" in $$source)) {
            /**
             * @member
             * @type {LegacyRuntimeStatus}
             */
            this["after"] = (new LegacyRuntimeStatus());
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {ShellStatus}
             */
            this["shell"] = (new ShellStatus());
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["actions"] = [];
        }
        if (!("requiresConfirmation" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresConfirmation"] = false;
        }
        if (!("forceUsed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["forceUsed"] = false;
        }
        if (!("hotkeyRetried" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hotkeyRetried"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LegacyHandoffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LegacyHandoffResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("before" in $$parsedSource) {
            $$parsedSource["before"] = $$createField2_0($$parsedSource["before"]);
        }
        if ("after" in $$parsedSource) {
            $$parsedSource["after"] = $$createField3_0($$parsedSource["after"]);
        }
        if ("shell" in $$parsedSource) {
            $$parsedSource["shell"] = $$createField4_0($$parsedSource["shell"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField5_0($$parsedSource["actions"]);
        }
        return new LegacyHandoffResult(/** @type {Partial<LegacyHandoffResult>} */($$parsedSource));
    }
}

export class LegacyRuntimeStatus {
    /**
     * Creates a new LegacyRuntimeStatus instance.
     * @param {Partial<LegacyRuntimeStatus>} [$$source = {}] - The source object to create the LegacyRuntimeStatus.
     */
    constructor($$source = {}) {
        if (!("processRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["processRunning"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["processId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["processName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["processPath"] = undefined;
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (!("configExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configExists"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["configBytes"] = undefined;
        }
        if (!("hotkeyConflictLikely" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hotkeyConflictLikely"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["notes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LegacyRuntimeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LegacyRuntimeStatus}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField8_0($$parsedSource["notes"]);
        }
        return new LegacyRuntimeStatus(/** @type {Partial<LegacyRuntimeStatus>} */($$parsedSource));
    }
}

export class LogStatus {
    /**
     * Creates a new LogStatus instance.
     * @param {Partial<LogStatus>} [$$source = {}] - The source object to create the LogStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("directoryExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["directoryExists"] = false;
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastModifiedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogStatus(/** @type {Partial<LogStatus>} */($$parsedSource));
    }
}

export class RuntimeDiagnostics {
    /**
     * Creates a new RuntimeDiagnostics instance.
     * @param {Partial<RuntimeDiagnostics>} [$$source = {}] - The source object to create the RuntimeDiagnostics.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("processId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["processId"] = 0;
        }
        if (!("workingDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workingDir"] = "";
        }
        if (!("executablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executablePath"] = "";
        }
        if (!("executableBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["executableBytes"] = 0;
        }
        if (!("appDataEnv" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appDataEnv"] = "";
        }
        if (!("localAppDataEnv" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAppDataEnv"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["goToolPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["wailsToolPath"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeDiagnostics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeDiagnostics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeDiagnostics(/** @type {Partial<RuntimeDiagnostics>} */($$parsedSource));
    }
}

export class RuntimeMetric {
    /**
     * Creates a new RuntimeMetric instance.
     * @param {Partial<RuntimeMetric>} [$$source = {}] - The source object to create the RuntimeMetric.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("unit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeMetric instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeMetric}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeMetric(/** @type {Partial<RuntimeMetric>} */($$parsedSource));
    }
}

export class SearchPerformanceStatus {
    /**
     * Creates a new SearchPerformanceStatus instance.
     * @param {Partial<SearchPerformanceStatus>} [$$source = {}] - The source object to create the SearchPerformanceStatus.
     */
    constructor($$source = {}) {
        if (!("sampleCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sampleCount"] = 0;
        }
        if (!("targetP95Ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetP95Ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastQuery"] = undefined;
        }
        if (!("lastElapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastElapsedMs"] = 0;
        }
        if (!("lastResultCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastResultCount"] = 0;
        }
        if (!("averageMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["averageMs"] = 0;
        }
        if (!("p95Ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["p95Ms"] = 0;
        }
        if (!("maxMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxMs"] = 0;
        }
        if (!("withinTarget" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["withinTarget"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastUpdatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchPerformanceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchPerformanceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchPerformanceStatus(/** @type {Partial<SearchPerformanceStatus>} */($$parsedSource));
    }
}

export class ShellStatus {
    /**
     * Creates a new ShellStatus instance.
     * @param {Partial<ShellStatus>} [$$source = {}] - The source object to create the ShellStatus.
     */
    constructor($$source = {}) {
        if (!("singleInstanceConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["singleInstanceConfigured"] = false;
        }
        if (!("trayConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["trayConfigured"] = false;
        }
        if (!("globalHotkeyRegistered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["globalHotkeyRegistered"] = false;
        }
        if (!("globalHotkey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["globalHotkey"] = "";
        }
        if (!("screenshotHotkeyRegistered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["screenshotHotkeyRegistered"] = false;
        }
        if (!("screenshotHotkey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenshotHotkey"] = "";
        }
        if (!("pinClipboardHotkeyRegistered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinClipboardHotkeyRegistered"] = false;
        }
        if (!("pinClipboardHotkey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pinClipboardHotkey"] = "";
        }
        if (!("autostartSupported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autostartSupported"] = false;
        }
        if (!("autostartEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autostartEnabled"] = false;
        }
        if (!("autostartPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["autostartPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["autostartIdentifier"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["autostartValueName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["autostartCommand"] = undefined;
        }
        if (!("autostartCommandValid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autostartCommandValid"] = false;
        }
        if (!("autostartHiddenArgPresent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autostartHiddenArgPresent"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["autostartNotes"] = undefined;
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShellStatus}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("autostartNotes" in $$parsedSource) {
            $$parsedSource["autostartNotes"] = $$createField16_0($$parsedSource["autostartNotes"]);
        }
        return new ShellStatus(/** @type {Partial<ShellStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Capability.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = RuntimeDiagnostics.createFrom;
const $$createType4 = ShellStatus.createFrom;
const $$createType5 = LegacyRuntimeStatus.createFrom;
const $$createType6 = SearchPerformanceStatus.createFrom;
const $$createType7 = FileSearchStatus.createFrom;
const $$createType8 = LogStatus.createFrom;
const $$createType9 = RuntimeMetric.createFrom;
const $$createType10 = $Create.Array($$createType9);
