// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {contracts$0.PreviewAction} action
 * @returns {$CancellablePromise<contracts$0.ActionResult>}
 */
export function ExecuteAction(action) {
    return $Call.ByID(3381641353, action).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DiagnosticsExportResult>}
 */
export function ExportDiagnostics() {
    return $Call.ByID(4270980690).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<contracts$0.ActionResult>}
 */
export function InstallFileSearchService() {
    return $Call.ByID(2781707380).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.LegacyHandoffRequest} request
 * @returns {$CancellablePromise<$models.LegacyHandoffResult>}
 */
export function ResolveLegacyConflict(request) {
    return $Call.ByID(1287151989, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.EnvironmentStatus>}
 */
export function Status() {
    return $Call.ByID(1113902454).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.ActionResult.createFrom;
const $$createType1 = $models.DiagnosticsExportResult.createFrom;
const $$createType2 = $models.LegacyHandoffResult.createFrom;
const $$createType3 = $models.EnvironmentStatus.createFrom;
