// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.CompareRequest} request
 * @returns {$CancellablePromise<$models.CompareResult>}
 */
export function Compare(request) {
    return $Call.ByID(2641094893, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.FormatRequest} request
 * @returns {$CancellablePromise<$models.FormatResult>}
 */
export function Format(request) {
    return $Call.ByID(2801292389, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CompareResult.createFrom;
const $$createType1 = $models.FormatResult.createFrom;
