// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workmemory$0 from "../workmemory/models.js";

export class DraftSaveRequest {
    /**
     * Creates a new DraftSaveRequest instance.
     * @param {Partial<DraftSaveRequest>} [$$source = {}] - The source object to create the DraftSaveRequest.
     */
    constructor($$source = {}) {
        if (!("draft" in $$source)) {
            /**
             * @member
             * @type {workmemory$0.WorkflowDraft}
             */
            this["draft"] = (new workmemory$0.WorkflowDraft());
        }
        if (!("confirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DraftSaveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DraftSaveRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("draft" in $$parsedSource) {
            $$parsedSource["draft"] = $$createField0_0($$parsedSource["draft"]);
        }
        return new DraftSaveRequest(/** @type {Partial<DraftSaveRequest>} */($$parsedSource));
    }
}

export class DraftSaveResult {
    /**
     * Creates a new DraftSaveResult instance.
     * @param {Partial<DraftSaveResult>} [$$source = {}] - The source object to create the DraftSaveResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Workflow | undefined}
             */
            this["workflow"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = (new Status());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["riskReasons"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DraftSaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DraftSaveResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workflow" in $$parsedSource) {
            $$parsedSource["workflow"] = $$createField2_0($$parsedSource["workflow"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        if ("riskReasons" in $$parsedSource) {
            $$parsedSource["riskReasons"] = $$createField5_0($$parsedSource["riskReasons"]);
        }
        return new DraftSaveResult(/** @type {Partial<DraftSaveResult>} */($$parsedSource));
    }
}

export class ExportResult {
    /**
     * Creates a new ExportResult instance.
     * @param {Partial<ExportResult>} [$$source = {}] - The source object to create the ExportResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["json"] = undefined;
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["exportedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult(/** @type {Partial<ExportResult>} */($$parsedSource));
    }
}

export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("importedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["importedCount"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = (new Status());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

export class RunRequest {
    /**
     * Creates a new RunRequest instance.
     * @param {Partial<RunRequest>} [$$source = {}] - The source object to create the RunRequest.
     */
    constructor($$source = {}) {
        if (!("workflowId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflowId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clipboardText"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["confirmed"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunRequest(/** @type {Partial<RunRequest>} */($$parsedSource));
    }
}

export class RunResult {
    /**
     * Creates a new RunResult instance.
     * @param {Partial<RunResult>} [$$source = {}] - The source object to create the RunResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("workflowId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflowId"] = "";
        }
        if (!("workflowName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflowName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {StepRun[]}
             */
            this["steps"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["riskReasons"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType5;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField5_0($$parsedSource["steps"]);
        }
        if ("riskReasons" in $$parsedSource) {
            $$parsedSource["riskReasons"] = $$createField7_0($$parsedSource["riskReasons"]);
        }
        return new RunResult(/** @type {Partial<RunResult>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("legacyPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["legacyPath"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSaveError"] = undefined;
        }
        if (!("legacyImported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["legacyImported"] = false;
        }
        if (!("workflows" in $$source)) {
            /**
             * @member
             * @type {Workflow[]}
             */
            this["workflows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workflows" in $$parsedSource) {
            $$parsedSource["workflows"] = $$createField5_0($$parsedSource["workflows"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

export class Step {
    /**
     * Creates a new Step instance.
     * @param {Partial<Step>} [$$source = {}] - The source object to create the Step.
     */
    constructor($$source = {}) {
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pick"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Step}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Step(/** @type {Partial<Step>} */($$parsedSource));
    }
}

export class StepRun {
    /**
     * Creates a new StepRun instance.
     * @param {Partial<StepRun>} [$$source = {}] - The source object to create the StepRun.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("renderedCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["renderedCommand"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pick"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pickedTitle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepRun instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StepRun}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StepRun(/** @type {Partial<StepRun>} */($$parsedSource));
    }
}

export class Workflow {
    /**
     * Creates a new Workflow instance.
     * @param {Partial<Workflow>} [$$source = {}] - The source object to create the Workflow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {Step[]}
             */
            this["steps"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workflow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField3_0($$parsedSource["steps"]);
        }
        return new Workflow(/** @type {Partial<Workflow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = workmemory$0.WorkflowDraft.createFrom;
const $$createType1 = Workflow.createFrom;
const $$createType2 = Status.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = StepRun.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType1);
const $$createType7 = Step.createFrom;
const $$createType8 = $Create.Array($$createType7);
