// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capturehistory$0 from "../capturehistory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pinnedimage$0 from "../pinnedimage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as qrscan$0 from "../qrscan/models.js";

export class AnnotationOperation {
    /**
     * Creates a new AnnotationOperation instance.
     * @param {Partial<AnnotationOperation>} [$$source = {}] - The source object to create the AnnotationOperation.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["endX"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["endY"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["color"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["strokeWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pixelSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AnnotationPoint[] | undefined}
             */
            this["points"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["fontSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["number"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnnotationOperation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnnotationOperation}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField10_0($$parsedSource["points"]);
        }
        return new AnnotationOperation(/** @type {Partial<AnnotationOperation>} */($$parsedSource));
    }
}

export class AnnotationPoint {
    /**
     * Creates a new AnnotationPoint instance.
     * @param {Partial<AnnotationPoint>} [$$source = {}] - The source object to create the AnnotationPoint.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnnotationPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnnotationPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnnotationPoint(/** @type {Partial<AnnotationPoint>} */($$parsedSource));
    }
}

export class CaptureResult {
    /**
     * Creates a new CaptureResult instance.
     * @param {Partial<CaptureResult>} [$$source = {}] - The source object to create the CaptureResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["captureId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["imagePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["savedPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {qrscan$0.Result | null | undefined}
             */
            this["qr"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {pinnedimage$0.OpenResult | null | undefined}
             */
            this["pin"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("qr" in $$parsedSource) {
            $$parsedSource["qr"] = $$createField7_0($$parsedSource["qr"]);
        }
        if ("pin" in $$parsedSource) {
            $$parsedSource["pin"] = $$createField8_0($$parsedSource["pin"]);
        }
        return new CaptureResult(/** @type {Partial<CaptureResult>} */($$parsedSource));
    }
}

export class OpenResult {
    /**
     * Creates a new OpenResult instance.
     * @param {Partial<OpenResult>} [$$source = {}] - The source object to create the OpenResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sessionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {capturehistory$0.ScreenBounds | undefined}
             */
            this["bounds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {capturehistory$0.ScreenBounds | undefined}
             */
            this["nativeBounds"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField3_0($$parsedSource["bounds"]);
        }
        if ("nativeBounds" in $$parsedSource) {
            $$parsedSource["nativeBounds"] = $$createField4_0($$parsedSource["nativeBounds"]);
        }
        return new OpenResult(/** @type {Partial<OpenResult>} */($$parsedSource));
    }
}

export class ScreenshotPolicy {
    /**
     * Creates a new ScreenshotPolicy instance.
     * @param {Partial<ScreenshotPolicy>} [$$source = {}] - The source object to create the ScreenshotPolicy.
     */
    constructor($$source = {}) {
        if (!("AutoCopy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoCopy"] = false;
        }
        if (!("AutoPin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoPin"] = false;
        }
        if (!("AutoSave" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoSave"] = false;
        }
        if (!("SaveDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SaveDir"] = "";
        }
        if (!("FilenameTemplate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FilenameTemplate"] = "";
        }
        if (!("AutoRedact" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoRedact"] = false;
        }
        if (!("RedactPhones" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["RedactPhones"] = false;
        }
        if (!("RedactKeywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["RedactKeywords"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenshotPolicy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenshotPolicy}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RedactKeywords" in $$parsedSource) {
            $$parsedSource["RedactKeywords"] = $$createField7_0($$parsedSource["RedactKeywords"]);
        }
        return new ScreenshotPolicy(/** @type {Partial<ScreenshotPolicy>} */($$parsedSource));
    }
}

export class SelectionRequest {
    /**
     * Creates a new SelectionRequest instance.
     * @param {Partial<SelectionRequest>} [$$source = {}] - The source object to create the SelectionRequest.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["coordinateSpace"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["displayWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["displayHeight"] = undefined;
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["savedPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["pinPositioned"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pinX"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pinY"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AnnotationOperation[] | undefined}
             */
            this["operations"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["renderedImage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SelectionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("operations" in $$parsedSource) {
            $$parsedSource["operations"] = $$createField13_0($$parsedSource["operations"]);
        }
        return new SelectionRequest(/** @type {Partial<SelectionRequest>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("bounds" in $$source)) {
            /**
             * @member
             * @type {capturehistory$0.ScreenBounds}
             */
            this["bounds"] = (new capturehistory$0.ScreenBounds());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {capturehistory$0.ScreenBounds | undefined}
             */
            this["nativeBounds"] = undefined;
        }
        if (!("imageUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageUrl"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField1_0($$parsedSource["bounds"]);
        }
        if ("nativeBounds" in $$parsedSource) {
            $$parsedSource["nativeBounds"] = $$createField2_0($$parsedSource["nativeBounds"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AnnotationPoint.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = qrscan$0.Result.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = pinnedimage$0.OpenResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = capturehistory$0.ScreenBounds.createFrom;
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = AnnotationOperation.createFrom;
const $$createType9 = $Create.Array($$createType8);
