// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.ScreenshotPolicy} policy
 * @returns {$CancellablePromise<void>}
 */
export function ApplyScreenshotPolicy(policy) {
    return $Call.ByID(3777847259, policy);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function Attach(app) {
    return $Call.ByID(2215866318, app);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.CaptureResult>}
 */
export function Cancel(id) {
    return $Call.ByID(4067222021, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.SelectionRequest} request
 * @returns {$CancellablePromise<$models.CaptureResult>}
 */
export function CaptureSelection(request) {
    return $Call.ByID(2672711471, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Session>}
 */
export function GetSession(id) {
    return $Call.ByID(3076436223, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function Open() {
    return $Call.ByID(2323458255).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.SelectionRequest} request
 * @returns {$CancellablePromise<$models.CaptureResult>}
 */
export function PrepareSelectionRedaction(request) {
    return $Call.ByID(37989261, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CaptureResult.createFrom;
const $$createType1 = $models.Session.createFrom;
const $$createType2 = $models.OpenResult.createFrom;
