// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capturehistory$0 from "../capturehistory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clipboardhistory$0 from "../clipboardhistory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.NoteRequest} request
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function AddNote(request) {
    return $Call.ByID(1979942046, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.CapturePolicy} policy
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ApplyCapturePolicy(policy) {
    return $Call.ByID(1636531183, policy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.DraftPolishPolicy} policy
 * @returns {$CancellablePromise<void>}
 */
export function ApplyDraftPolishPolicy(policy) {
    return $Call.ByID(3091088535, policy);
}

/**
 * @param {$models.DraftSchedulePolicy} policy
 * @returns {$CancellablePromise<$models.ScheduledDraftStatus>}
 */
export function ApplyDraftSchedule(policy) {
    return $Call.ByID(840578605, policy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.EmbeddingPolicy} policy
 * @returns {$CancellablePromise<$models.SemanticStatus>}
 */
export function ApplyEmbeddingPolicy(policy) {
    return $Call.ByID(3161769208, policy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {$models.ExperienceDiscoveryPolicy} policy
 * @returns {$CancellablePromise<void>}
 */
export function ApplyExperienceDiscoveryPolicy(policy) {
    return $Call.ByID(3807077023, policy);
}

/**
 * @param {$models.FlowAgentPolicy} policy
 * @returns {$CancellablePromise<void>}
 */
export function ApplyFlowAgentPolicy(policy) {
    return $Call.ByID(1239943620, policy);
}

/**
 * @param {$models.FlowAutonomyPolicy} policy
 * @returns {$CancellablePromise<$models.FlowAutonomyStatus>}
 */
export function ApplyFlowAutonomyPolicy(policy) {
    return $Call.ByID(1644171177, policy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.OCRSummaryPolicy} policy
 * @returns {$CancellablePromise<void>}
 */
export function ApplyOCRSummaryPolicy(policy) {
    return $Call.ByID(3007072791, policy);
}

/**
 * @param {string} id
 * @param {string} text
 * @param {string} provider
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function ApplyOCRText(id, text, provider) {
    return $Call.ByID(4191099972, id, text, provider).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} retentionDays
 * @param {boolean} keepFavorites
 * @returns {$CancellablePromise<$models.RetentionResult>}
 */
export function ApplyRetentionPolicy(retentionDays, keepFavorites) {
    return $Call.ByID(3468497631, retentionDays, keepFavorites).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {boolean} enabled
 * @param {boolean} privacyMode
 * @param {boolean} timeMachineEnabled
 * @param {number} intervalSeconds
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ApplySettings(enabled, privacyMode, timeMachineEnabled, intervalSeconds) {
    return $Call.ByID(2264642516, enabled, privacyMode, timeMachineEnabled, intervalSeconds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.FlowAskRequest} request
 * @returns {$CancellablePromise<$models.FlowAskResponse>}
 */
export function AskFlow(request) {
    return $Call.ByID(417763280, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.FlowConversationAskRequest} request
 * @returns {$CancellablePromise<$models.FlowConversationAskResult>}
 */
export function AskFlowConversation(request) {
    return $Call.ByID(1047314903, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AutonomousArtifact[]>}
 */
export function AutonomousArtifacts() {
    return $Call.ByID(960718462).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function CaptureCurrentScreen() {
    return $Call.ByID(2222261316).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function CaptureTimeMachineNow() {
    return $Call.ByID(3158710497).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function CaptureTimeMachineWindowSwitch() {
    return $Call.ByID(28882423).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ClearUnpinned() {
    return $Call.ByID(3820956325).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<$models.FlowConversation>}
 */
export function CreateFlowConversation(title) {
    return $Call.ByID(2065427700, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {$models.FlowCandidateActionDecisionRequest} request
 * @returns {$CancellablePromise<$models.FlowCandidateActionDecisionResult>}
 */
export function DecideFlowCandidateAction(request) {
    return $Call.ByID(2218477070, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Delete(id) {
    return $Call.ByID(488342452, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.FlowConversation[]>}
 */
export function DeleteFlowConversation(id) {
    return $Call.ByID(1715489323, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.SelfModel>}
 */
export function DeleteSelfAssertion(id) {
    return $Call.ByID(2183329770, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.TodoList>}
 */
export function DeleteTodo(id) {
    return $Call.ByID(2882125116, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {number} periodDays
 * @returns {$CancellablePromise<$models.ExperienceReport>}
 */
export function DiscoverExperiences(periodDays) {
    return $Call.ByID(3127362081, periodDays).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {$models.ExperienceDiscoveryRequest} request
 * @returns {$CancellablePromise<$models.ExperienceDiscoveryResult>}
 */
export function DiscoverExperiencesAI(request) {
    return $Call.ByID(4109429835, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function Entry(id) {
    return $Call.ByID(3382188737, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {boolean} includeSensitive
 * @returns {$CancellablePromise<$models.ExportResult>}
 */
export function ExportData(includeSensitive) {
    return $Call.ByID(2509923253, includeSensitive).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {$models.ExportRequest} request
 * @returns {$CancellablePromise<$models.ExportResult>}
 */
export function ExportDataWithOptions(request) {
    return $Call.ByID(715353761, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.FlowAutonomyStatus>}
 */
export function FlowAutonomyStatus() {
    return $Call.ByID(1403385759).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.FlowCandidateActionListRequest} request
 * @returns {$CancellablePromise<$models.FlowCandidateActionList>}
 */
export function FlowCandidateActions(request) {
    return $Call.ByID(2349449871, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.FlowConversation[]>}
 */
export function FlowConversations() {
    return $Call.ByID(1356733789).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} conversationID
 * @returns {$CancellablePromise<$models.FlowMessage[]>}
 */
export function FlowMessages(conversationID) {
    return $Call.ByID(1381636251, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {string} goal
 * @param {string[]} evidence
 * @returns {$CancellablePromise<$models.AgentTaskPackage>}
 */
export function GenerateAgentTaskPackage(goal, evidence) {
    return $Call.ByID(3355711264, goal, evidence).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {string} title
 * @param {string[]} evidence
 * @returns {$CancellablePromise<$models.ChecklistDraft>}
 */
export function GenerateChecklistDraft(title, evidence) {
    return $Call.ByID(3602889123, title, evidence).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Draft>}
 */
export function GenerateDailyDraft() {
    return $Call.ByID(1512268104).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @param {string[]} requestedIDs
 * @returns {$CancellablePromise<$models.Draft>}
 */
export function GenerateKnowledgeDraft(requestedIDs) {
    return $Call.ByID(834729239, requestedIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<$models.Draft>}
 */
export function GenerateRetrospectiveDraft(ids) {
    return $Call.ByID(3598430440, ids).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @param {string} title
 * @param {string[]} evidence
 * @returns {$CancellablePromise<$models.WorkflowDraft>}
 */
export function GenerateWorkflowDraft(title, evidence) {
    return $Call.ByID(830337844, title, evidence).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.HealthSummary>}
 */
export function HealthSummary() {
    return $Call.ByID(3381529391).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @param {$models.Entry[]} entries
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ImportLegacyEntries(entries) {
    return $Call.ByID(1232375827, entries).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ImportMaterialRequest} request
 * @returns {$CancellablePromise<$models.ImportMaterialResult>}
 */
export function ImportMaterials(request) {
    return $Call.ByID(1093064920, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function LegacyEntryCount() {
    return $Call.ByID(3379615115);
}

/**
 * @param {$models.DraftPolishRequest} request
 * @returns {$CancellablePromise<$models.DraftPolishResult>}
 */
export function PolishDraft(request) {
    return $Call.ByID(1554284901, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.EmbeddingRefreshResult>}
 */
export function RefreshEmbeddingIndex() {
    return $Call.ByID(3228022749).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @param {$models.AutonomousArtifactRejectRequest} request
 * @returns {$CancellablePromise<$models.AutonomousArtifactRejectResult>}
 */
export function RejectAutonomousArtifact(request) {
    return $Call.ByID(567803582, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * @param {capturehistory$0.Entry} entry
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function RememberCaptureHistoryEntry(entry) {
    return $Call.ByID(3295188866, entry).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {clipboardhistory$0.Entry} entry
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function RememberClipboardEntry(entry) {
    return $Call.ByID(2704140702, entry).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.QualityReviewResult>}
 */
export function ReviewPendingCaptures() {
    return $Call.ByID(2976925757).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AutonomousRunResult>}
 */
export function RunAutonomousFlowNow() {
    return $Call.ByID(2230000304).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.FlowAutonomyRunResult>}
 */
export function RunFlowAutonomyNow() {
    return $Call.ByID(2496076310).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ScheduledDraftStatus>}
 */
export function RunScheduledDraftsNow() {
    return $Call.ByID(109080057).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ScheduledDraftStatus>}
 */
export function ScheduledDraftStatus() {
    return $Call.ByID(3926511503).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<contracts$0.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(1720770567, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SelfModel>}
 */
export function SelfModel() {
    return $Call.ByID(2941314558).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<$models.SemanticSearchResult>}
 */
export function SemanticSearchExternal(query) {
    return $Call.ByID(349971404, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SemanticStatus>}
 */
export function SemanticStatus() {
    return $Call.ByID(3591745729).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} insightID
 * @param {string} status
 * @param {string} note
 * @param {string} taskPackageID
 * @returns {$CancellablePromise<$models.ExperienceDecisionResult>}
 */
export function SetExperienceInsightDecision(insightID, status, note, taskPackageID) {
    return $Call.ByID(3962404189, insightID, status, note, taskPackageID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.Status>}
 */
export function SetPrivacyMode(enabled) {
    return $Call.ByID(181693736, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.Status>}
 */
export function SetTimeMachineEnabled(enabled) {
    return $Call.ByID(3235597082, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(262877233).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(3905578079);
}

/**
 * @returns {$CancellablePromise<$models.Entry[]>}
 */
export function Timeline() {
    return $Call.ByID(1998909596).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @param {$models.TodoListRequest} request
 * @returns {$CancellablePromise<$models.TodoList>}
 */
export function Todos(request) {
    return $Call.ByID(636776492, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {$models.TodoUpdateRequest} request
 * @returns {$CancellablePromise<$models.TodoList>}
 */
export function UpdateTodo(request) {
    return $Call.ByID(3526392822, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {$models.SelfAssertionRequest} request
 * @returns {$CancellablePromise<$models.SelfModel>}
 */
export function UpsertSelfAssertion(request) {
    return $Call.ByID(113284562, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {$models.TodoRequest} request
 * @returns {$CancellablePromise<$models.TodoList>}
 */
export function UpsertTodo(request) {
    return $Call.ByID(449346964, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Entry.createFrom;
const $$createType1 = $models.Status.createFrom;
const $$createType2 = $models.ScheduledDraftStatus.createFrom;
const $$createType3 = $models.SemanticStatus.createFrom;
const $$createType4 = $models.FlowAutonomyStatus.createFrom;
const $$createType5 = $models.RetentionResult.createFrom;
const $$createType6 = $models.FlowAskResponse.createFrom;
const $$createType7 = $models.FlowConversationAskResult.createFrom;
const $$createType8 = $models.AutonomousArtifact.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.FlowConversation.createFrom;
const $$createType11 = $models.FlowCandidateActionDecisionResult.createFrom;
const $$createType12 = $Create.Array($$createType10);
const $$createType13 = $models.SelfModel.createFrom;
const $$createType14 = $models.TodoList.createFrom;
const $$createType15 = $models.ExperienceReport.createFrom;
const $$createType16 = $models.ExperienceDiscoveryResult.createFrom;
const $$createType17 = $models.ExportResult.createFrom;
const $$createType18 = $models.FlowCandidateActionList.createFrom;
const $$createType19 = $models.FlowMessage.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.AgentTaskPackage.createFrom;
const $$createType22 = $models.ChecklistDraft.createFrom;
const $$createType23 = $models.Draft.createFrom;
const $$createType24 = $models.WorkflowDraft.createFrom;
const $$createType25 = $models.HealthSummary.createFrom;
const $$createType26 = $models.ImportMaterialResult.createFrom;
const $$createType27 = $models.DraftPolishResult.createFrom;
const $$createType28 = $models.EmbeddingRefreshResult.createFrom;
const $$createType29 = $models.AutonomousArtifactRejectResult.createFrom;
const $$createType30 = $models.QualityReviewResult.createFrom;
const $$createType31 = $models.AutonomousRunResult.createFrom;
const $$createType32 = $models.FlowAutonomyRunResult.createFrom;
const $$createType33 = contracts$0.SearchResult.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = $models.SemanticSearchResult.createFrom;
const $$createType36 = $models.ExperienceDecisionResult.createFrom;
const $$createType37 = $Create.Array($$createType0);
