// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ocr$0 from "../ocr/models.js";

export class BatchResult {
    /**
     * Creates a new BatchResult instance.
     * @param {Partial<BatchResult>} [$$source = {}] - The source object to create the BatchResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (!("finishedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["finishedAt"] = 0;
        }
        if (!("indexed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexed"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Entry[] | undefined}
             */
            this["entries"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField7_0($$parsedSource["entries"]);
        }
        return new BatchResult(/** @type {Partial<BatchResult>} */($$parsedSource));
    }
}

export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }
        if (!("imagePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imagePath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ocr$0.Line[] | undefined}
             */
            this["lines"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["createdAt"] = undefined;
        }
        if (!("indexedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexedAt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("sensitive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sensitive"] = false;
        }
        if (!("redacted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["redacted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["recognizedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField5_0($$parsedSource["lines"]);
        }
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}

export class IndexRequest {
    /**
     * Creates a new IndexRequest instance.
     * @param {Partial<IndexRequest>} [$$source = {}] - The source object to create the IndexRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["sources"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["limit"] = undefined;
        }
        if (!("force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IndexRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField0_0($$parsedSource["sources"]);
        }
        return new IndexRequest(/** @type {Partial<IndexRequest>} */($$parsedSource));
    }
}

export class RetentionResult {
    /**
     * Creates a new RetentionResult instance.
     * @param {Partial<RetentionResult>} [$$source = {}] - The source object to create the RetentionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("retentionDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retentionDays"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cutoffAt"] = undefined;
        }
        if (!("removed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removed"] = 0;
        }
        if (!("removedStale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removedStale"] = 0;
        }
        if (!("removedExpired" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removedExpired"] = 0;
        }
        if (!("kept" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["kept"] = 0;
        }
        if (!("remainingCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remainingCount"] = 0;
        }
        if (!("appliedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["appliedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetentionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RetentionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RetentionResult(/** @type {Partial<RetentionResult>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("indexedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexedCount"] = 0;
        }
        if (!("sensitiveCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sensitiveCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastRunAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastIndexedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (!("ocrAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ocrAvailable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ocrProvider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Entry[] | undefined}
             */
            this["entries"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField10_0($$parsedSource["entries"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ocr$0.Line.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
