// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {number} retentionDays
 * @returns {$CancellablePromise<$models.RetentionResult>}
 */
export function ApplyRetentionPolicy(retentionDays) {
    return $Call.ByID(2949223980, retentionDays).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} captureID
 * @param {boolean} force
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function IndexCapture(captureID, force) {
    return $Call.ByID(338349378, captureID, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} clipboardID
 * @param {boolean} force
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function IndexClipboardImage(clipboardID, force) {
    return $Call.ByID(85205299, clipboardID, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.IndexRequest} request
 * @returns {$CancellablePromise<$models.BatchResult>}
 */
export function IndexRecent(request) {
    return $Call.ByID(2997737803, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.Entry[]>}
 */
export function List(query, limit) {
    return $Call.ByID(327999148, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<contracts$0.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(1981454872, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(439661838).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.RetentionResult.createFrom;
const $$createType1 = $models.Entry.createFrom;
const $$createType2 = $models.BatchResult.createFrom;
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = contracts$0.SearchResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Status.createFrom;
