// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CollectCurrentResult {
    /**
     * Creates a new CollectCurrentResult instance.
     * @param {Partial<CollectCurrentResult>} [$$source = {}] - The source object to create the CollectCurrentResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Entry | undefined}
             */
            this["entry"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = (new Status());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectCurrentResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectCurrentResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField2_0($$parsedSource["entry"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        return new CollectCurrentResult(/** @type {Partial<CollectCurrentResult>} */($$parsedSource));
    }
}

export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {EntryType}
             */
            this["type"] = EntryType.$zero;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["imagePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["thumbnailPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["thumbnailWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["thumbnailHeight"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["thumbnailBytes"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("signature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["signature"] = "";
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        const $$createField17_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField17_0($$parsedSource["tags"]);
        }
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const EntryType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    EntryText: "text",
    EntryImage: "image",
};

export class RetentionResult {
    /**
     * Creates a new RetentionResult instance.
     * @param {Partial<RetentionResult>} [$$source = {}] - The source object to create the RetentionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("retentionDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retentionDays"] = 0;
        }
        if (!("keepPinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepPinned"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cutoffAt"] = undefined;
        }
        if (!("removed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removed"] = 0;
        }
        if (!("removedImages" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removedImages"] = 0;
        }
        if (!("kept" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["kept"] = 0;
        }
        if (!("keptPinned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keptPinned"] = 0;
        }
        if (!("remainingCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remainingCount"] = 0;
        }
        if (!("appliedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["appliedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetentionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RetentionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RetentionResult(/** @type {Partial<RetentionResult>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("imageDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageDir"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["thumbnailDir"] = undefined;
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("pinnedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pinnedCount"] = 0;
        }
        if (!("imageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["imageCount"] = 0;
        }
        if (!("thumbnailCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thumbnailCount"] = 0;
        }
        if (!("thumbnailBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thumbnailBytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastEntryAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSaveError"] = undefined;
        }
        if (!("watcherEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["watcherEnabled"] = false;
        }
        if (!("watcherRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["watcherRunning"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastWatcherAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastWatcherError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Entry[] | undefined}
             */
            this["entries"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField14_0($$parsedSource["entries"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Entry.createFrom;
const $$createType1 = Status.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType0);
