// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capturehistory$0 from "../capturehistory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as qrscan$0 from "../qrscan/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<capturehistory$0.Status>}
 */
export function AddImageToCapture(id) {
    return $Call.ByID(2712048224, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} pngBytes
 * @param {string} source
 * @returns {$CancellablePromise<$models.Status>}
 */
export function AddPNG(pngBytes, source) {
    return $Call.ByID(2392408573, pngBytes, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} text
 * @param {string} source
 * @returns {$CancellablePromise<$models.Status>}
 */
export function AddText(text, source) {
    return $Call.ByID(3314935017, text, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} retentionDays
 * @param {boolean} keepPinned
 * @returns {$CancellablePromise<$models.RetentionResult>}
 */
export function ApplyRetentionPolicy(retentionDays, keepPinned) {
    return $Call.ByID(767131215, retentionDays, keepPinned).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {boolean} privacyMode
 * @param {boolean} sourceClipboard
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ApplyWatcherSettings(privacyMode, sourceClipboard) {
    return $Call.ByID(2353658222, privacyMode, sourceClipboard).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ClearUnpinned() {
    return $Call.ByID(842872533).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<$models.Status>}
 */
export function CollectCurrent(source) {
    return $Call.ByID(34236780, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<$models.CollectCurrentResult>}
 */
export function CollectCurrentEntry(source) {
    return $Call.ByID(1651169312, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<contracts$0.ActionResult>}
 */
export function CopyImage(id) {
    return $Call.ByID(2157294091, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<qrscan$0.Result>}
 */
export function DecodeImageQRCode(id) {
    return $Call.ByID(3570300660, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Delete(id) {
    return $Call.ByID(3701346244, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function Entry(id) {
    return $Call.ByID(2934459185, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ImageDataURL(id) {
    return $Call.ByID(1158745741, id);
}

/**
 * @param {$models.Entry[]} entries
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ImportLegacyEntries(entries) {
    return $Call.ByID(3378904003, entries).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function LegacyEntryCount() {
    return $Call.ByID(162981563);
}

/**
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.Entry[]>}
 */
export function List(query, limit) {
    return $Call.ByID(2895310207, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<contracts$0.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(4204949495, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(190764737).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function StopWatcher() {
    return $Call.ByID(1729922641).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ThumbnailDataURL(id) {
    return $Call.ByID(822279910, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function TogglePin(id) {
    return $Call.ByID(337660898, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = capturehistory$0.Status.createFrom;
const $$createType1 = $models.Status.createFrom;
const $$createType2 = $models.RetentionResult.createFrom;
const $$createType3 = $models.CollectCurrentResult.createFrom;
const $$createType4 = contracts$0.ActionResult.createFrom;
const $$createType5 = qrscan$0.Result.createFrom;
const $$createType6 = $models.Entry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = contracts$0.SearchResult.createFrom;
const $$createType9 = $Create.Array($$createType8);
