// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Assertion {
    /**
     * Creates a new Assertion instance.
     * @param {Partial<Assertion>} [$$source = {}] - The source object to create the Assertion.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("operator" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operator"] = "";
        }
        if (!("expected" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expected"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assertion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Assertion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Assertion(/** @type {Partial<Assertion>} */($$parsedSource));
    }
}

export class AssertionResult {
    /**
     * Creates a new AssertionResult instance.
     * @param {Partial<AssertionResult>} [$$source = {}] - The source object to create the AssertionResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("operator" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operator"] = "";
        }
        if (!("expected" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expected"] = "";
        }
        if (!("actual" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actual"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssertionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssertionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssertionResult(/** @type {Partial<AssertionResult>} */($$parsedSource));
    }
}

export class Collection {
    /**
     * Creates a new Collection instance.
     * @param {Partial<Collection>} [$$source = {}] - The source object to create the Collection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {Variable[]}
             */
            this["variables"] = [];
        }
        if (!("environments" in $$source)) {
            /**
             * @member
             * @type {Environment[]}
             */
            this["environments"] = [];
        }
        if (!("requests" in $$source)) {
            /**
             * @member
             * @type {Request[]}
             */
            this["requests"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GitConfig | undefined}
             */
            this["git"] = undefined;
        }
        if (!("activeEnvironmentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeEnvironmentId"] = "";
        }
        if (!("activeRequestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeRequestId"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Collection}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField2_0($$parsedSource["variables"]);
        }
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField3_0($$parsedSource["environments"]);
        }
        if ("requests" in $$parsedSource) {
            $$parsedSource["requests"] = $$createField4_0($$parsedSource["requests"]);
        }
        if ("git" in $$parsedSource) {
            $$parsedSource["git"] = $$createField5_0($$parsedSource["git"]);
        }
        return new Collection(/** @type {Partial<Collection>} */($$parsedSource));
    }
}

export class Environment {
    /**
     * Creates a new Environment instance.
     * @param {Partial<Environment>} [$$source = {}] - The source object to create the Environment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {Variable[]}
             */
            this["variables"] = [];
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Environment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Environment}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField2_0($$parsedSource["variables"]);
        }
        return new Environment(/** @type {Partial<Environment>} */($$parsedSource));
    }
}

export class GitConfig {
    /**
     * Creates a new GitConfig instance.
     * @param {Partial<GitConfig>} [$$source = {}] - The source object to create the GitConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remote"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["branch"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitConfig(/** @type {Partial<GitConfig>} */($$parsedSource));
    }
}

export class GitStatus {
    /**
     * Creates a new GitStatus instance.
     * @param {Partial<GitStatus>} [$$source = {}] - The source object to create the GitStatus.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collectionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remote"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["branch"] = undefined;
        }
        if (!("dirty" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dirty"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["files"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitStatus}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField7_0($$parsedSource["files"]);
        }
        return new GitStatus(/** @type {Partial<GitStatus>} */($$parsedSource));
    }
}

export class Header {
    /**
     * Creates a new Header instance.
     * @param {Partial<Header>} [$$source = {}] - The source object to create the Header.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Header instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Header}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Header(/** @type {Partial<Header>} */($$parsedSource));
    }
}

export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("importedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["importedCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = (new Status());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField4_0($$parsedSource["status"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

export class Param {
    /**
     * Creates a new Param instance.
     * @param {Partial<Param>} [$$source = {}] - The source object to create the Param.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Param instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Param}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Param(/** @type {Partial<Param>} */($$parsedSource));
    }
}

export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("bodyType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyType"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("params" in $$source)) {
            /**
             * @member
             * @type {Param[]}
             */
            this["params"] = [];
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {Header[]}
             */
            this["headers"] = [];
        }
        if (!("assertions" in $$source)) {
            /**
             * @member
             * @type {Assertion[]}
             */
            this["assertions"] = [];
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType12;
        const $$createField9_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField7_0($$parsedSource["params"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField8_0($$parsedSource["headers"]);
        }
        if ("assertions" in $$parsedSource) {
            $$parsedSource["assertions"] = $$createField9_0($$parsedSource["assertions"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

export class RunRequest {
    /**
     * Creates a new RunRequest instance.
     * @param {Partial<RunRequest>} [$$source = {}] - The source object to create the RunRequest.
     */
    constructor($$source = {}) {
        if (!("collectionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collectionId"] = "";
        }
        if (!("environmentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["environmentId"] = "";
        }
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {Request}
             */
            this["request"] = (new Request());
        }
        if (!("timeoutSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeoutSeconds"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["runId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["stream"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField2_0($$parsedSource["request"]);
        }
        return new RunRequest(/** @type {Partial<RunRequest>} */($$parsedSource));
    }
}

export class RunResult {
    /**
     * Creates a new RunResult instance.
     * @param {Partial<RunResult>} [$$source = {}] - The source object to create the RunResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("requestUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestUrl"] = "";
        }
        if (!("statusCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["statusCode"] = 0;
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {Header[]}
             */
            this["headers"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("bodySize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bodySize"] = 0;
        }
        if (!("bodyTruncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bodyTruncated"] = false;
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["streaming"] = undefined;
        }
        if (!("assertionResults" in $$source)) {
            /**
             * @member
             * @type {AssertionResult[]}
             */
            this["assertionResults"] = [];
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["passed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["missingVariables"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType12;
        const $$createField13_0 = $$createType16;
        const $$createField17_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField7_0($$parsedSource["headers"]);
        }
        if ("assertionResults" in $$parsedSource) {
            $$parsedSource["assertionResults"] = $$createField13_0($$parsedSource["assertionResults"]);
        }
        if ("missingVariables" in $$parsedSource) {
            $$parsedSource["missingVariables"] = $$createField17_0($$parsedSource["missingVariables"]);
        }
        return new RunResult(/** @type {Partial<RunResult>} */($$parsedSource));
    }
}

export class RunSnapshot {
    /**
     * Creates a new RunSnapshot instance.
     * @param {Partial<RunSnapshot>} [$$source = {}] - The source object to create the RunSnapshot.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {RunResult}
             */
            this["result"] = (new RunResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField4_0($$parsedSource["result"]);
        }
        return new RunSnapshot(/** @type {Partial<RunSnapshot>} */($$parsedSource));
    }
}

export class RunStopResult {
    /**
     * Creates a new RunStopResult instance.
     * @param {Partial<RunStopResult>} [$$source = {}] - The source object to create the RunStopResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunStopResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunStopResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunStopResult(/** @type {Partial<RunStopResult>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("databasePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databasePath"] = "";
        }
        if (!("collections" in $$source)) {
            /**
             * @member
             * @type {Collection[]}
             */
            this["collections"] = [];
        }
        if (!("activeCollectionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeCollectionId"] = "";
        }
        if (!("collectionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["collectionCount"] = 0;
        }
        if (!("requestCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSaveError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastLoadError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField2_0($$parsedSource["collections"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

export class Variable {
    /**
     * Creates a new Variable instance.
     * @param {Partial<Variable>} [$$source = {}] - The source object to create the Variable.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["secret"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Variable instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Variable}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Variable(/** @type {Partial<Variable>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Variable.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Environment.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Request.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = GitConfig.createFrom;
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = Status.createFrom;
const $$createType9 = Param.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Header.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Assertion.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = AssertionResult.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = RunResult.createFrom;
const $$createType18 = Collection.createFrom;
const $$createType19 = $Create.Array($$createType18);
