// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} collectionID
 * @param {string} repoPath
 * @param {string} remote
 * @returns {$CancellablePromise<$models.GitStatus>}
 */
export function ConfigureGit(collectionID, repoPath, remote) {
    return $Call.ByID(2728000477, collectionID, repoPath, remote).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} collectionID
 * @param {string} message
 * @returns {$CancellablePromise<$models.GitStatus>}
 */
export function GitCommitPush(collectionID, message) {
    return $Call.ByID(3592585638, collectionID, message).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} collectionID
 * @returns {$CancellablePromise<$models.GitStatus>}
 */
export function GitPull(collectionID) {
    return $Call.ByID(4246945576, collectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} collectionID
 * @returns {$CancellablePromise<$models.GitStatus>}
 */
export function GitStatus(collectionID) {
    return $Call.ByID(270975137, collectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} path
 * @param {string} collectionID
 * @returns {$CancellablePromise<$models.ImportResult>}
 */
export function ImportRequests(path, collectionID) {
    return $Call.ByID(801190630, path, collectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function NewCollection() {
    return $Call.ByID(413372449).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function RemoveCollection(id) {
    return $Call.ByID(4077014221, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.RunRequest} request
 * @returns {$CancellablePromise<$models.RunResult>}
 */
export function Run(request) {
    return $Call.ByID(3818441750, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<$models.RunSnapshot>}
 */
export function RunSnapshot(runID) {
    return $Call.ByID(3868544650, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function SetActiveCollection(id) {
    return $Call.ByID(593930805, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(53237355).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<$models.RunStopResult>}
 */
export function StopRun(runID) {
    return $Call.ByID(2088425414, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.Collection} next
 * @returns {$CancellablePromise<$models.Status>}
 */
export function UpsertCollection(next) {
    return $Call.ByID(3043594358, next).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.GitStatus.createFrom;
const $$createType1 = $models.ImportResult.createFrom;
const $$createType2 = $models.Status.createFrom;
const $$createType3 = $models.RunResult.createFrom;
const $$createType4 = $models.RunSnapshot.createFrom;
const $$createType5 = $models.RunStopResult.createFrom;
