// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workmemory$0 from "../workmemory/models.js";

export class AIOCRPolicy {
    /**
     * Creates a new AIOCRPolicy instance.
     * @param {Partial<AIOCRPolicy>} [$$source = {}] - The source object to create the AIOCRPolicy.
     */
    constructor($$source = {}) {
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("Provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Provider"] = "";
        }
        if (!("BaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["BaseURL"] = "";
        }
        if (!("Model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIOCRPolicy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIOCRPolicy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIOCRPolicy(/** @type {Partial<AIOCRPolicy>} */($$parsedSource));
    }
}

export class Line {
    /**
     * Creates a new Line instance.
     * @param {Partial<Line>} [$$source = {}] - The source object to create the Line.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("confidence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidence"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Rect | undefined}
             */
            this["rect"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Line instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Line}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rect" in $$parsedSource) {
            $$parsedSource["rect"] = $$createField2_0($$parsedSource["rect"]);
        }
        return new Line(/** @type {Partial<Line>} */($$parsedSource));
    }
}

export class Rect {
    /**
     * Creates a new Rect instance.
     * @param {Partial<Rect>} [$$source = {}] - The source object to create the Rect.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rect instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rect}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rect(/** @type {Partial<Rect>} */($$parsedSource));
    }
}

export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Line[] | undefined}
             */
            this["lines"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["captureId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clipboardId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["memoryId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["imagePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["elapsedMs"] = undefined;
        }
        if (!("sensitive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sensitive"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["recognizedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {workmemory$0.Entry | null | undefined}
             */
            this["workMemory"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField15_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField2_0($$parsedSource["lines"]);
        }
        if ("workMemory" in $$parsedSource) {
            $$parsedSource["workMemory"] = $$createField15_0($$parsedSource["workMemory"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pythonPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bridgePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastRunAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Rect.createFrom;
const $$createType1 = Line.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = workmemory$0.Entry.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
