// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.AIOCRPolicy} policy
 * @returns {$CancellablePromise<void>}
 */
export function ApplyAIOCRPolicy(policy) {
    return $Call.ByID(1352982841, policy);
}

/**
 * @returns {$CancellablePromise<$models.Result>}
 */
export function LastResult() {
    return $Call.ByID(3179850928).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} captureID
 * @returns {$CancellablePromise<$models.Result>}
 */
export function RecognizeCapture(captureID) {
    return $Call.ByID(2215879483, captureID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} clipboardID
 * @returns {$CancellablePromise<$models.Result>}
 */
export function RecognizeClipboardImage(clipboardID) {
    return $Call.ByID(1466927344, clipboardID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Result>}
 */
export function RecognizeCurrentScreen() {
    return $Call.ByID(2726057288).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.Result>}
 */
export function RecognizeImagePath(path) {
    return $Call.ByID(2898189711, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} memoryID
 * @returns {$CancellablePromise<$models.Result>}
 */
export function RecognizeWorkMemory(memoryID) {
    return $Call.ByID(2338712697, memoryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(3409889063).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Result.createFrom;
const $$createType1 = $models.Status.createFrom;
