// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActionFeedback {
    /**
     * Creates a new ActionFeedback instance.
     * @param {Partial<ActionFeedback>} [$$source = {}] - The source object to create the ActionFeedback.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["successLabel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionFeedback instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionFeedback}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionFeedback(/** @type {Partial<ActionFeedback>} */($$parsedSource));
    }
}

export class ActionResult {
    /**
     * Creates a new ActionResult instance.
     * @param {Partial<ActionResult>} [$$source = {}] - The source object to create the ActionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["riskReasons"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("riskReasons" in $$parsedSource) {
            $$parsedSource["riskReasons"] = $$createField3_0($$parsedSource["riskReasons"]);
        }
        return new ActionResult(/** @type {Partial<ActionResult>} */($$parsedSource));
    }
}

export class LabelValue {
    /**
     * Creates a new LabelValue instance.
     * @param {Partial<LabelValue>} [$$source = {}] - The source object to create the LabelValue.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LabelValue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LabelValue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LabelValue(/** @type {Partial<LabelValue>} */($$parsedSource));
    }
}

export class PreviewAction {
    /**
     * Creates a new PreviewAction instance.
     * @param {Partial<PreviewAction>} [$$source = {}] - The source object to create the PreviewAction.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["shortcut"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {PreviewActionKind}
             */
            this["kind"] = PreviewActionKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["payload"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ActionFeedback | null | undefined}
             */
            this["feedback"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewAction}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField5_0($$parsedSource["payload"]);
        }
        if ("feedback" in $$parsedSource) {
            $$parsedSource["feedback"] = $$createField6_0($$parsedSource["feedback"]);
        }
        return new PreviewAction(/** @type {Partial<PreviewAction>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const PreviewActionKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ActionOpen: "open",
    ActionOpenParent: "open_parent",
    ActionCopy: "copy",
    ActionPin: "pin",
    ActionRun: "run",
    ActionPlugin: "plugin",
    ActionRemember: "remember",
    ActionDanger: "danger",
};

export class PreviewDescriptor {
    /**
     * Creates a new PreviewDescriptor instance.
     * @param {Partial<PreviewDescriptor>} [$$source = {}] - The source object to create the PreviewDescriptor.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {PreviewKind}
             */
            this["kind"] = PreviewKind.$zero;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtitle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {LabelValue[] | undefined}
             */
            this["meta"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {LabelValue[] | undefined}
             */
            this["evidence"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["imageHint"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewDescriptor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewDescriptor}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField4_0($$parsedSource["meta"]);
        }
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField5_0($$parsedSource["evidence"]);
        }
        return new PreviewDescriptor(/** @type {Partial<PreviewDescriptor>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const PreviewKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PreviewText: "text",
    PreviewMemory: "memory",
    PreviewImage: "image",
    PreviewSettings: "settings",
    PreviewWorkflow: "workflow",
};

export class SearchResponse {
    /**
     * Creates a new SearchResponse instance.
     * @param {Partial<SearchResponse>} [$$source = {}] - The source object to create the SearchResponse.
     */
    constructor($$source = {}) {
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {SearchResult[]}
             */
            this["results"] = [];
        }
        if (!("elapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField1_0($$parsedSource["results"]);
        }
        return new SearchResponse(/** @type {Partial<SearchResponse>} */($$parsedSource));
    }
}

export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {SearchResultType}
             */
            this["type"] = SearchResultType.$zero;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtitle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["score"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["payload"] = undefined;
        }
        if (!("preview" in $$source)) {
            /**
             * @member
             * @type {PreviewDescriptor}
             */
            this["preview"] = (new PreviewDescriptor());
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {PreviewAction[]}
             */
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType8;
        const $$createField10_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField8_0($$parsedSource["payload"]);
        }
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField9_0($$parsedSource["preview"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField10_0($$parsedSource["actions"]);
        }
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const SearchResultType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ResultFile: "file",
    ResultApp: "app",
    ResultPluginTrigger: "plugin_trigger",
    ResultPluginResult: "plugin_result",
    ResultWorkflow: "workflow",
    ResultClipboard: "clipboard",
    ResultMemory: "memory",
    ResultCommand: "command",
    ResultCapture: "capture",
    ResultSettings: "settings",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = ActionFeedback.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = LabelValue.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SearchResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = PreviewDescriptor.createFrom;
const $$createType9 = PreviewAction.createFrom;
const $$createType10 = $Create.Array($$createType9);
