// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} data
 * @param {number} width
 * @param {number} height
 * @param {string} source
 * @param {string} savedPath
 * @param {string[]} actions
 * @returns {$CancellablePromise<$models.Status>}
 */
export function AddPNG(data, width, height, source, savedPath, actions) {
    return $Call.ByID(2757614249, data, width, height, source, savedPath, actions).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} retentionDays
 * @param {boolean} keepPinned
 * @returns {$CancellablePromise<$models.RetentionResult>}
 */
export function ApplyRetentionPolicy(retentionDays, keepPinned) {
    return $Call.ByID(661812299, retentionDays, keepPinned).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} maxStorageMB
 * @param {boolean} keepPinned
 * @returns {$CancellablePromise<$models.RetentionResult>}
 */
export function ApplyStoragePolicy(maxStorageMB, keepPinned) {
    return $Call.ByID(2319293608, maxStorageMB, keepPinned).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {number} height
 * @param {string} source
 * @param {string[]} actions
 * @returns {$CancellablePromise<$models.Status>}
 */
export function CaptureRegion(x, y, width, height, source, actions) {
    return $Call.ByID(118297667, x, y, width, height, source, actions).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<$models.Status>}
 */
export function CaptureScreen(source) {
    return $Call.ByID(2173338007, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} source
 * @param {$models.CaptureOptions} options
 * @returns {$CancellablePromise<$models.Status>}
 */
export function CaptureScreenWithOptions(source, options) {
    return $Call.ByID(660410523, source, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ClearUnpinned() {
    return $Call.ByID(1076882409).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Delete(id) {
    return $Call.ByID(2401482448, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function Entry(id) {
    return $Call.ByID(3770493037, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ImageDataURL(id) {
    return $Call.ByID(1297318625, id);
}

/**
 * @param {$models.Entry[]} entries
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ImportLegacyEntries(entries) {
    return $Call.ByID(3508400327, entries).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function LegacyEntryCount() {
    return $Call.ByID(2108391991);
}

/**
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.Entry[]>}
 */
export function List(query, limit) {
    return $Call.ByID(3582173403, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<contracts$0.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(2603872779, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(1154323941).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ThumbnailDataURL(id) {
    return $Call.ByID(1900960778, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Status>}
 */
export function TogglePin(id) {
    return $Call.ByID(956147486, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
const $$createType1 = $models.RetentionResult.createFrom;
const $$createType2 = $models.Entry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = contracts$0.SearchResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
