// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workmemory$0 from "../workmemory/models.js";

export class CodexInstalledSkill {
    /**
     * Creates a new CodexInstalledSkill instance.
     * @param {Partial<CodexInstalledSkill>} [$$source = {}] - The source object to create the CodexInstalledSkill.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("skillPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skillPath"] = "";
        }
        if (!("readable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["ariadneManaged"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexInstalledSkill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexInstalledSkill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexInstalledSkill(/** @type {Partial<CodexInstalledSkill>} */($$parsedSource));
    }
}

export class DraftSaveRequest {
    /**
     * Creates a new DraftSaveRequest instance.
     * @param {Partial<DraftSaveRequest>} [$$source = {}] - The source object to create the DraftSaveRequest.
     */
    constructor($$source = {}) {
        if (!("draft" in $$source)) {
            /**
             * @member
             * @type {workmemory$0.Draft}
             */
            this["draft"] = (new workmemory$0.Draft());
        }
        if (!("confirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DraftSaveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DraftSaveRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("draft" in $$parsedSource) {
            $$parsedSource["draft"] = $$createField0_0($$parsedSource["draft"]);
        }
        return new DraftSaveRequest(/** @type {Partial<DraftSaveRequest>} */($$parsedSource));
    }
}

export class DraftSaveResult {
    /**
     * Creates a new DraftSaveResult instance.
     * @param {Partial<DraftSaveResult>} [$$source = {}] - The source object to create the DraftSaveResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Skill | undefined}
             */
            this["skill"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = (new Status());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["riskReasons"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DraftSaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DraftSaveResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField2_0($$parsedSource["skill"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        if ("riskReasons" in $$parsedSource) {
            $$parsedSource["riskReasons"] = $$createField5_0($$parsedSource["riskReasons"]);
        }
        return new DraftSaveResult(/** @type {Partial<DraftSaveResult>} */($$parsedSource));
    }
}

export class ExportRequest {
    /**
     * Creates a new ExportRequest instance.
     * @param {Partial<ExportRequest>} [$$source = {}] - The source object to create the ExportRequest.
     */
    constructor($$source = {}) {
        if (!("skillId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skillId"] = "";
        }
        if (!("confirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRequest(/** @type {Partial<ExportRequest>} */($$parsedSource));
    }
}

export class ExportResult {
    /**
     * Creates a new ExportResult instance.
     * @param {Partial<ExportResult>} [$$source = {}] - The source object to create the ExportResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Skill | undefined}
             */
            this["skill"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["directory"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["zipPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["exportedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["riskReasons"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField2_0($$parsedSource["skill"]);
        }
        if ("riskReasons" in $$parsedSource) {
            $$parsedSource["riskReasons"] = $$createField8_0($$parsedSource["riskReasons"]);
        }
        return new ExportResult(/** @type {Partial<ExportResult>} */($$parsedSource));
    }
}

export class InstallDiagnosticsRequest {
    /**
     * Creates a new InstallDiagnosticsRequest instance.
     * @param {Partial<InstallDiagnosticsRequest>} [$$source = {}] - The source object to create the InstallDiagnosticsRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skillId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetRoot"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallDiagnosticsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallDiagnosticsRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallDiagnosticsRequest(/** @type {Partial<InstallDiagnosticsRequest>} */($$parsedSource));
    }
}

export class InstallDiagnosticsResult {
    /**
     * Creates a new InstallDiagnosticsResult instance.
     * @param {Partial<InstallDiagnosticsResult>} [$$source = {}] - The source object to create the InstallDiagnosticsResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("targetRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetRoot"] = "";
        }
        if (!("targetRootExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["targetRootExists"] = false;
        }
        if (!("targetRootReadable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["targetRootReadable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skillId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["installedDir"] = undefined;
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skillPath"] = undefined;
        }
        if (!("skillFileExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skillFileExists"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["skillFileBytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["skillUpdatedAt"] = undefined;
        }
        if (!("discoveredCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discoveredCount"] = 0;
        }
        if (!("ariadneManagedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ariadneManagedCount"] = 0;
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {CodexInstalledSkill[]}
             */
            this["skills"] = [];
        }
        if (!("refresh" in $$source)) {
            /**
             * @member
             * @type {RefreshDiagnostics}
             */
            this["refresh"] = (new RefreshDiagnostics());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallDiagnosticsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallDiagnosticsResult}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType5;
        const $$createField15_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField14_0($$parsedSource["skills"]);
        }
        if ("refresh" in $$parsedSource) {
            $$parsedSource["refresh"] = $$createField15_0($$parsedSource["refresh"]);
        }
        return new InstallDiagnosticsResult(/** @type {Partial<InstallDiagnosticsResult>} */($$parsedSource));
    }
}

export class InstallRequest {
    /**
     * Creates a new InstallRequest instance.
     * @param {Partial<InstallRequest>} [$$source = {}] - The source object to create the InstallRequest.
     */
    constructor($$source = {}) {
        if (!("skillId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skillId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetRoot"] = undefined;
        }
        if (!("confirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["overwrite"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallRequest(/** @type {Partial<InstallRequest>} */($$parsedSource));
    }
}

export class InstallResult {
    /**
     * Creates a new InstallResult instance.
     * @param {Partial<InstallResult>} [$$source = {}] - The source object to create the InstallResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Skill | undefined}
             */
            this["skill"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetRoot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["installedDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["files"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["installedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["refreshRequested"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["refreshMarker"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["refreshManifest"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["riskReasons"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField2_0($$parsedSource["skill"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField5_0($$parsedSource["files"]);
        }
        if ("riskReasons" in $$parsedSource) {
            $$parsedSource["riskReasons"] = $$createField11_0($$parsedSource["riskReasons"]);
        }
        return new InstallResult(/** @type {Partial<InstallResult>} */($$parsedSource));
    }
}

export class RefreshDiagnostics {
    /**
     * Creates a new RefreshDiagnostics instance.
     * @param {Partial<RefreshDiagnostics>} [$$source = {}] - The source object to create the RefreshDiagnostics.
     */
    constructor($$source = {}) {
        if (!("manifestPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manifestPath"] = "";
        }
        if (!("markerPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["markerPath"] = "";
        }
        if (!("manifestExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["manifestExists"] = false;
        }
        if (!("markerExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["markerExists"] = false;
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["action"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skillId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skillTitle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["installedDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["requestedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["markerId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["markerText"] = undefined;
        }
        if (!("markerMatchesManifest" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["markerMatchesManifest"] = false;
        }
        if (!("skillMatchesRequest" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skillMatchesRequest"] = false;
        }
        if (!("installedDirExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installedDirExists"] = false;
        }
        if (!("installedSkillFileFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installedSkillFileFound"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshDiagnostics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefreshDiagnostics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefreshDiagnostics(/** @type {Partial<RefreshDiagnostics>} */($$parsedSource));
    }
}

export class Skill {
    /**
     * Creates a new Skill instance.
     * @param {Partial<Skill>} [$$source = {}] - The source object to create the Skill.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("evidence" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["evidence"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["createdAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Skill}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField3_0($$parsedSource["evidence"]);
        }
        return new Skill(/** @type {Partial<Skill>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSaveError"] = undefined;
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {Skill[]}
             */
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField3_0($$parsedSource["skills"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = workmemory$0.Draft.createFrom;
const $$createType1 = Skill.createFrom;
const $$createType2 = Status.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = CodexInstalledSkill.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = RefreshDiagnostics.createFrom;
const $$createType7 = $Create.Array($$createType1);
