// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.ExportRequest} request
 * @returns {$CancellablePromise<$models.ExportResult>}
 */
export function ExportSkillPackage(request) {
    return $Call.ByID(367577282, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.InstallDiagnosticsRequest} request
 * @returns {$CancellablePromise<$models.InstallDiagnosticsResult>}
 */
export function InstallDiagnostics(request) {
    return $Call.ByID(3132017106, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.InstallRequest} request
 * @returns {$CancellablePromise<$models.InstallResult>}
 */
export function InstallSkillPackage(request) {
    return $Call.ByID(190818473, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Skill[]>}
 */
export function List() {
    return $Call.ByID(2426204451).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {$models.DraftSaveRequest} request
 * @returns {$CancellablePromise<$models.DraftSaveResult>}
 */
export function SaveSkillDraft(request) {
    return $Call.ByID(361868474, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Status() {
    return $Call.ByID(3746247661).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.Skill} next
 * @returns {$CancellablePromise<$models.Status>}
 */
export function Upsert(next) {
    return $Call.ByID(1765535000, next).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ExportResult.createFrom;
const $$createType1 = $models.InstallDiagnosticsResult.createFrom;
const $$createType2 = $models.InstallResult.createFrom;
const $$createType3 = $models.Skill.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.DraftSaveResult.createFrom;
const $$createType6 = $models.Status.createFrom;
