// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClearUsageResult {
    /**
     * Creates a new ClearUsageResult instance.
     * @param {Partial<ClearUsageResult>} [$$source = {}] - The source object to create the ClearUsageResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("cleared" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cleared"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {UsageStatus}
             */
            this["status"] = (new UsageStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClearUsageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClearUsageResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        return new ClearUsageResult(/** @type {Partial<ClearUsageResult>} */($$parsedSource));
    }
}

export class PerformanceStatus {
    /**
     * Creates a new PerformanceStatus instance.
     * @param {Partial<PerformanceStatus>} [$$source = {}] - The source object to create the PerformanceStatus.
     */
    constructor($$source = {}) {
        if (!("sampleCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sampleCount"] = 0;
        }
        if (!("targetP95Ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetP95Ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastQuery"] = undefined;
        }
        if (!("lastElapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastElapsedMs"] = 0;
        }
        if (!("lastResultCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastResultCount"] = 0;
        }
        if (!("averageMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["averageMs"] = 0;
        }
        if (!("p95Ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["p95Ms"] = 0;
        }
        if (!("maxMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxMs"] = 0;
        }
        if (!("withinTarget" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["withinTarget"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["lastUpdatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformanceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PerformanceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PerformanceStatus(/** @type {Partial<PerformanceStatus>} */($$parsedSource));
    }
}

export class UsageRecord {
    /**
     * Creates a new UsageRecord instance.
     * @param {Partial<UsageRecord>} [$$source = {}] - The source object to create the UsageRecord.
     */
    constructor($$source = {}) {
        if (!("resultId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resultId"] = "";
        }
        if (!("favorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["favorite"] = false;
        }
        if (!("useCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["useCount"] = 0;
        }
        if (!("lastUsedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastUsedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageRecord(/** @type {Partial<UsageRecord>} */($$parsedSource));
    }
}

export class UsageStatus {
    /**
     * Creates a new UsageStatus instance.
     * @param {Partial<UsageStatus>} [$$source = {}] - The source object to create the UsageStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("records" in $$source)) {
            /**
             * @member
             * @type {UsageRecord[]}
             */
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageStatus}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField2_0($$parsedSource["records"]);
        }
        return new UsageStatus(/** @type {Partial<UsageStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = UsageStatus.createFrom;
const $$createType1 = UsageRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
