// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.ClearUsageResult>}
 */
export function ClearUsage() {
    return $Call.ByID(3130902977).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PerformanceStatus>}
 */
export function PerformanceStatus() {
    return $Call.ByID(2439441675).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} resultID
 * @returns {$CancellablePromise<$models.UsageRecord>}
 */
export function RecordUse(resultID) {
    return $Call.ByID(2924520771, resultID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<contracts$0.SearchResponse>}
 */
export function Search(query) {
    return $Call.ByID(3483618237, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} resultID
 * @param {boolean} favorite
 * @returns {$CancellablePromise<$models.UsageRecord>}
 */
export function SetFavorite(resultID, favorite) {
    return $Call.ByID(2595236295, resultID, favorite).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UsageStatus>}
 */
export function UsageStatus() {
    return $Call.ByID(3683141998).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ClearUsageResult.createFrom;
const $$createType1 = $models.PerformanceStatus.createFrom;
const $$createType2 = $models.UsageRecord.createFrom;
const $$createType3 = contracts$0.SearchResponse.createFrom;
const $$createType4 = $models.UsageStatus.createFrom;
