// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workmemory$0 from "../workmemory/models.js";

export class Checklist {
    /**
     * Creates a new Checklist instance.
     * @param {Partial<Checklist>} [$$source = {}] - The source object to create the Checklist.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["context"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["items"] = [];
        }
        if (!("evidence" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["evidence"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["createdAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Checklist instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Checklist}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField4_0($$parsedSource["evidence"]);
        }
        return new Checklist(/** @type {Partial<Checklist>} */($$parsedSource));
    }
}

export class DraftSaveRequest {
    /**
     * Creates a new DraftSaveRequest instance.
     * @param {Partial<DraftSaveRequest>} [$$source = {}] - The source object to create the DraftSaveRequest.
     */
    constructor($$source = {}) {
        if (!("draft" in $$source)) {
            /**
             * @member
             * @type {workmemory$0.ChecklistDraft}
             */
            this["draft"] = (new workmemory$0.ChecklistDraft());
        }
        if (!("confirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DraftSaveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DraftSaveRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("draft" in $$parsedSource) {
            $$parsedSource["draft"] = $$createField0_0($$parsedSource["draft"]);
        }
        return new DraftSaveRequest(/** @type {Partial<DraftSaveRequest>} */($$parsedSource));
    }
}

export class DraftSaveResult {
    /**
     * Creates a new DraftSaveResult instance.
     * @param {Partial<DraftSaveResult>} [$$source = {}] - The source object to create the DraftSaveResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Checklist | undefined}
             */
            this["checklist"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = (new Status());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requiresConfirmation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["riskReasons"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DraftSaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DraftSaveResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checklist" in $$parsedSource) {
            $$parsedSource["checklist"] = $$createField2_0($$parsedSource["checklist"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        if ("riskReasons" in $$parsedSource) {
            $$parsedSource["riskReasons"] = $$createField5_0($$parsedSource["riskReasons"]);
        }
        return new DraftSaveResult(/** @type {Partial<DraftSaveResult>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSaveError"] = undefined;
        }
        if (!("checklists" in $$source)) {
            /**
             * @member
             * @type {Checklist[]}
             */
            this["checklists"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checklists" in $$parsedSource) {
            $$parsedSource["checklists"] = $$createField3_0($$parsedSource["checklists"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = workmemory$0.ChecklistDraft.createFrom;
const $$createType2 = Checklist.createFrom;
const $$createType3 = Status.createFrom;
const $$createType4 = $Create.Array($$createType2);
