// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BackupRequest {
    /**
     * Creates a new BackupRequest instance.
     * @param {Partial<BackupRequest>} [$$source = {}] - The source object to create the BackupRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupRequest(/** @type {Partial<BackupRequest>} */($$parsedSource));
    }
}

export class BackupResult {
    /**
     * Creates a new BackupResult instance.
     * @param {Partial<BackupResult>} [$$source = {}] - The source object to create the BackupResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("roots" in $$source)) {
            /**
             * @member
             * @type {DataRootStatus[]}
             */
            this["roots"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roots" in $$parsedSource) {
            $$parsedSource["roots"] = $$createField5_0($$parsedSource["roots"]);
        }
        return new BackupResult(/** @type {Partial<BackupResult>} */($$parsedSource));
    }
}

export class BackupStatus {
    /**
     * Creates a new BackupStatus instance.
     * @param {Partial<BackupStatus>} [$$source = {}] - The source object to create the BackupStatus.
     */
    constructor($$source = {}) {
        if (!("dataRoots" in $$source)) {
            /**
             * @member
             * @type {DataRootStatus[]}
             */
            this["dataRoots"] = [];
        }
        if (!("backupDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupDir"] = "";
        }
        if (!("backupCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backupCount"] = 0;
        }
        if (!("backupBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backupBytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestBackup"] = undefined;
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupStatus}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dataRoots" in $$parsedSource) {
            $$parsedSource["dataRoots"] = $$createField0_0($$parsedSource["dataRoots"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField5_0($$parsedSource["notes"]);
        }
        return new BackupStatus(/** @type {Partial<BackupStatus>} */($$parsedSource));
    }
}

export class DataRootStatus {
    /**
     * Creates a new DataRootStatus instance.
     * @param {Partial<DataRootStatus>} [$$source = {}] - The source object to create the DataRootStatus.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("archiveName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archiveName"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataRootStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataRootStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataRootStatus(/** @type {Partial<DataRootStatus>} */($$parsedSource));
    }
}

export class RestoreRequest {
    /**
     * Creates a new RestoreRequest instance.
     * @param {Partial<RestoreRequest>} [$$source = {}] - The source object to create the RestoreRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("confirm" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirm"] = false;
        }
        if (!("createPreRestoreBackup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["createPreRestoreBackup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RestoreRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoreRequest(/** @type {Partial<RestoreRequest>} */($$parsedSource));
    }
}

export class RestoreResult {
    /**
     * Creates a new RestoreResult instance.
     * @param {Partial<RestoreResult>} [$$source = {}] - The source object to create the RestoreResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["preRestoreBackupPath"] = undefined;
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("roots" in $$source)) {
            /**
             * @member
             * @type {RestoreRootResult[]}
             */
            this["roots"] = [];
        }
        if (!("requiresConfirmation" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresConfirmation"] = false;
        }
        if (!("restoredAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restoredAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RestoreResult}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roots" in $$parsedSource) {
            $$parsedSource["roots"] = $$createField6_0($$parsedSource["roots"]);
        }
        return new RestoreResult(/** @type {Partial<RestoreResult>} */($$parsedSource));
    }
}

export class RestoreRootResult {
    /**
     * Creates a new RestoreRootResult instance.
     * @param {Partial<RestoreRootResult>} [$$source = {}] - The source object to create the RestoreRootResult.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("archiveName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archiveName"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("restoredFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restoredFiles"] = 0;
        }
        if (!("restoredBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restoredBytes"] = 0;
        }
        if (!("skippedFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skippedFiles"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestoreRootResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RestoreRootResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RestoreRootResult(/** @type {Partial<RestoreRootResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DataRootStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = RestoreRootResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
