// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommandParam {
    /**
     * Creates a new CommandParam instance.
     * @param {Partial<CommandParam>} [$$source = {}] - The source object to create the CommandParam.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("placeholder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandParam instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandParam}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandParam(/** @type {Partial<CommandParam>} */($$parsedSource));
    }
}

export class CommandSchema {
    /**
     * Creates a new CommandSchema instance.
     * @param {Partial<CommandSchema>} [$$source = {}] - The source object to create the CommandSchema.
     */
    constructor($$source = {}) {
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usage"] = "";
        }
        if (!("examples" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["examples"] = [];
        }
        if (!("params" in $$source)) {
            /**
             * @member
             * @type {CommandParam[]}
             */
            this["params"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandSchema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandSchema}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("examples" in $$parsedSource) {
            $$parsedSource["examples"] = $$createField1_0($$parsedSource["examples"]);
        }
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField2_0($$parsedSource["params"]);
        }
        return new CommandSchema(/** @type {Partial<CommandSchema>} */($$parsedSource));
    }
}

export class PluginManifest {
    /**
     * Creates a new PluginManifest instance.
     * @param {Partial<PluginManifest>} [$$source = {}] - The source object to create the PluginManifest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("keywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keywords"] = [];
        }
        if (!("supportedPlatforms" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["supportedPlatforms"] = [];
        }
        if (!("requiredCapabilities" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["requiredCapabilities"] = [];
        }
        if (!("commandSchema" in $$source)) {
            /**
             * @member
             * @type {CommandSchema}
             */
            this["commandSchema"] = (new CommandSchema());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginManifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginManifest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField3_0($$parsedSource["keywords"]);
        }
        if ("supportedPlatforms" in $$parsedSource) {
            $$parsedSource["supportedPlatforms"] = $$createField4_0($$parsedSource["supportedPlatforms"]);
        }
        if ("requiredCapabilities" in $$parsedSource) {
            $$parsedSource["requiredCapabilities"] = $$createField5_0($$parsedSource["requiredCapabilities"]);
        }
        if ("commandSchema" in $$parsedSource) {
            $$parsedSource["commandSchema"] = $$createField6_0($$parsedSource["commandSchema"]);
        }
        return new PluginManifest(/** @type {Partial<PluginManifest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CommandParam.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = CommandSchema.createFrom;
