// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {{ [_ in string]?: boolean }} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ApplyEnabled(enabled) {
    return $Call.ByID(1998415744, enabled);
}

/**
 * @param {string} keyword
 * @param {string} query
 * @returns {$CancellablePromise<contracts$0.SearchResult[]>}
 */
export function Execute(keyword, query) {
    return $Call.ByID(1927845144, keyword, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PluginManifest[]>}
 */
export function List() {
    return $Call.ByID(2477534977).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<contracts$0.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(2985567017, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.SearchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PluginManifest.createFrom;
const $$createType3 = $Create.Array($$createType2);
