// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AISettings {
    /**
     * Creates a new AISettings instance.
     * @param {Partial<AISettings>} [$$source = {}] - The source object to create the AISettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("ocrModelEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ocrModelEnabled"] = false;
        }
        if (!("ocrProvider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ocrProvider"] = "";
        }
        if (!("ocrBaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ocrBaseUrl"] = "";
        }
        if (!("ocrModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ocrModel"] = "";
        }
        if (!("embeddingEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["embeddingEnabled"] = false;
        }
        if (!("embeddingProvider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embeddingProvider"] = "";
        }
        if (!("embeddingBaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embeddingBaseUrl"] = "";
        }
        if (!("embeddingModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embeddingModel"] = "";
        }
        if (!("vectorStoreType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vectorStoreType"] = "";
        }
        if (!("vectorStoreUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vectorStoreUri"] = "";
        }
        if (!("vectorCollection" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vectorCollection"] = "";
        }
        if (!("agentsSdkEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["agentsSdkEnabled"] = false;
        }
        if (!("traceMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["traceMode"] = "";
        }
        if (!("opscoreSyncEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["opscoreSyncEnabled"] = false;
        }
        if (!("externalAgentEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["externalAgentEnabled"] = false;
        }
        if (!("codexCollaborationEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["codexCollaborationEnabled"] = false;
        }
        if (!("externalAgentTaskDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["externalAgentTaskDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AISettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISettings(/** @type {Partial<AISettings>} */($$parsedSource));
    }
}

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("general" in $$source)) {
            /**
             * @member
             * @type {GeneralSettings}
             */
            this["general"] = (new GeneralSettings());
        }
        if (!("hotkeys" in $$source)) {
            /**
             * @member
             * @type {Hotkeys}
             */
            this["hotkeys"] = (new Hotkeys());
        }
        if (!("screenshot" in $$source)) {
            /**
             * @member
             * @type {ScreenshotSettings}
             */
            this["screenshot"] = (new ScreenshotSettings());
        }
        if (!("workMemory" in $$source)) {
            /**
             * @member
             * @type {WorkMemorySettings}
             */
            this["workMemory"] = (new WorkMemorySettings());
        }
        if (!("ai" in $$source)) {
            /**
             * @member
             * @type {AISettings}
             */
            this["ai"] = (new AISettings());
        }
        if (!("plugins" in $$source)) {
            /**
             * @member
             * @type {PluginSettings}
             */
            this["plugins"] = (new PluginSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("general" in $$parsedSource) {
            $$parsedSource["general"] = $$createField1_0($$parsedSource["general"]);
        }
        if ("hotkeys" in $$parsedSource) {
            $$parsedSource["hotkeys"] = $$createField2_0($$parsedSource["hotkeys"]);
        }
        if ("screenshot" in $$parsedSource) {
            $$parsedSource["screenshot"] = $$createField3_0($$parsedSource["screenshot"]);
        }
        if ("workMemory" in $$parsedSource) {
            $$parsedSource["workMemory"] = $$createField4_0($$parsedSource["workMemory"]);
        }
        if ("ai" in $$parsedSource) {
            $$parsedSource["ai"] = $$createField5_0($$parsedSource["ai"]);
        }
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField6_0($$parsedSource["plugins"]);
        }
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class GeneralSettings {
    /**
     * Creates a new GeneralSettings instance.
     * @param {Partial<GeneralSettings>} [$$source = {}] - The source object to create the GeneralSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("runOnStartup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["runOnStartup"] = false;
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GeneralSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneralSettings(/** @type {Partial<GeneralSettings>} */($$parsedSource));
    }
}

export class Hotkeys {
    /**
     * Creates a new Hotkeys instance.
     * @param {Partial<Hotkeys>} [$$source = {}] - The source object to create the Hotkeys.
     */
    constructor($$source = {}) {
        if (!("toggleWindow" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toggleWindow"] = "";
        }
        if (!("screenshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenshot"] = "";
        }
        if (!("pinClipboard" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pinClipboard"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hotkeys instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Hotkeys}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hotkeys(/** @type {Partial<Hotkeys>} */($$parsedSource));
    }
}

export class LegacyConfigStatus {
    /**
     * Creates a new LegacyConfigStatus instance.
     * @param {Partial<LegacyConfigStatus>} [$$source = {}] - The source object to create the LegacyConfigStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("needsImport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsImport"] = false;
        }
        if (!("importedKeys" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["importedKeys"] = [];
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LegacyConfigStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LegacyConfigStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("importedKeys" in $$parsedSource) {
            $$parsedSource["importedKeys"] = $$createField3_0($$parsedSource["importedKeys"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField4_0($$parsedSource["notes"]);
        }
        return new LegacyConfigStatus(/** @type {Partial<LegacyConfigStatus>} */($$parsedSource));
    }
}

export class PluginSettings {
    /**
     * Creates a new PluginSettings instance.
     * @param {Partial<PluginSettings>} [$$source = {}] - The source object to create the PluginSettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["enabled"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enabled" in $$parsedSource) {
            $$parsedSource["enabled"] = $$createField0_0($$parsedSource["enabled"]);
        }
        return new PluginSettings(/** @type {Partial<PluginSettings>} */($$parsedSource));
    }
}

export class ScreenshotSettings {
    /**
     * Creates a new ScreenshotSettings instance.
     * @param {Partial<ScreenshotSettings>} [$$source = {}] - The source object to create the ScreenshotSettings.
     */
    constructor($$source = {}) {
        if (!("autoCopy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoCopy"] = false;
        }
        if (!("autoPin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoPin"] = false;
        }
        if (!("autoSave" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoSave"] = false;
        }
        if (!("saveDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveDir"] = "";
        }
        if (!("filenameTemplate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filenameTemplate"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quality"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenshotSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenshotSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenshotSettings(/** @type {Partial<ScreenshotSettings>} */($$parsedSource));
    }
}

export class StorageStatus {
    /**
     * Creates a new StorageStatus instance.
     * @param {Partial<StorageStatus>} [$$source = {}] - The source object to create the StorageStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("directoryExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["directoryExists"] = false;
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("readBackOk" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readBackOk"] = false;
        }
        if (!("readBackBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["readBackBytes"] = 0;
        }
        if (!("readBackVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["readBackVersion"] = 0;
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["entries"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["virtualizedPath"] = undefined;
        }
        if (!("virtualizedExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["virtualizedExists"] = false;
        }
        if (!("virtualizedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["virtualizedBytes"] = 0;
        }
        if (!("appDataEnv" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appDataEnv"] = "";
        }
        if (!("localAppDataEnv" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAppDataEnv"] = "";
        }
        if (!("userConfigDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userConfigDir"] = "";
        }
        if (!("workingDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workingDir"] = "";
        }
        if (!("executablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executablePath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSaveError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["readBackError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageStatus}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField8_0($$parsedSource["entries"]);
        }
        return new StorageStatus(/** @type {Partial<StorageStatus>} */($$parsedSource));
    }
}

export class WorkMemoryAppCaptureProfile {
    /**
     * Creates a new WorkMemoryAppCaptureProfile instance.
     * @param {Partial<WorkMemoryAppCaptureProfile>} [$$source = {}] - The source object to create the WorkMemoryAppCaptureProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("processName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["processName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("windowSwitchDelaySeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowSwitchDelaySeconds"] = 0;
        }
        if (!("activeIntervalSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeIntervalSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkMemoryAppCaptureProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkMemoryAppCaptureProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkMemoryAppCaptureProfile(/** @type {Partial<WorkMemoryAppCaptureProfile>} */($$parsedSource));
    }
}

export class WorkMemorySettings {
    /**
     * Creates a new WorkMemorySettings instance.
     * @param {Partial<WorkMemorySettings>} [$$source = {}] - The source object to create the WorkMemorySettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("timeMachineEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["timeMachineEnabled"] = false;
        }
        if (!("autoCaptureIntervalSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["autoCaptureIntervalSeconds"] = 0;
        }
        if (!("windowSwitchCaptureEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["windowSwitchCaptureEnabled"] = false;
        }
        if (!("windowSwitchCooldownSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowSwitchCooldownSeconds"] = 0;
        }
        if (!("appCaptureProfiles" in $$source)) {
            /**
             * @member
             * @type {WorkMemoryAppCaptureProfile[]}
             */
            this["appCaptureProfiles"] = [];
        }
        if (!("captureScope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["captureScope"] = "";
        }
        if (!("screenshotQuality" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["screenshotQuality"] = 0;
        }
        if (!("multiMonitor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["multiMonitor"] = "";
        }
        if (!("privacyMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["privacyMode"] = false;
        }
        if (!("pauseOnIdle" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pauseOnIdle"] = false;
        }
        if (!("idlePauseSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idlePauseSeconds"] = 0;
        }
        if (!("pauseOnLock" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pauseOnLock"] = false;
        }
        if (!("sourceClipboard" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sourceClipboard"] = false;
        }
        if (!("sourceCaptureHistory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sourceCaptureHistory"] = false;
        }
        if (!("sourceManualNote" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sourceManualNote"] = false;
        }
        if (!("sourceSearchFavorite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sourceSearchFavorite"] = false;
        }
        if (!("sourceActions" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sourceActions"] = false;
        }
        if (!("autoOcr" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoOcr"] = false;
        }
        if (!("draftScheduleEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["draftScheduleEnabled"] = false;
        }
        if (!("draftScheduleIntervalMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["draftScheduleIntervalMinutes"] = 0;
        }
        if (!("dailyDraftScheduleEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dailyDraftScheduleEnabled"] = false;
        }
        if (!("retrospectiveDraftScheduleEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["retrospectiveDraftScheduleEnabled"] = false;
        }
        if (!("experienceScheduleEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["experienceScheduleEnabled"] = false;
        }
        if (!("experienceDiscoveryEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["experienceDiscoveryEnabled"] = false;
        }
        if (!("experienceDiscoveryDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["experienceDiscoveryDays"] = 0;
        }
        if (!("skillSuggestionEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skillSuggestionEnabled"] = false;
        }
        if (!("workflowSuggestionEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["workflowSuggestionEnabled"] = false;
        }
        if (!("retentionDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retentionDays"] = 0;
        }
        if (!("thumbnailRetentionDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thumbnailRetentionDays"] = 0;
        }
        if (!("maxStorageMb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxStorageMb"] = 0;
        }
        if (!("keepFavoritesForever" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepFavoritesForever"] = false;
        }
        if (!("excludeApps" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["excludeApps"] = [];
        }
        if (!("excludeWindowKeywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["excludeWindowKeywords"] = [];
        }
        if (!("excludePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["excludePaths"] = [];
        }
        if (!("excludeUrls" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["excludeUrls"] = [];
        }
        if (!("excludeContentPatterns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["excludeContentPatterns"] = [];
        }
        if (!("sensitiveRulesEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sensitiveRulesEnabled"] = false;
        }
        if (!("allowSensitiveExport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allowSensitiveExport"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkMemorySettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkMemorySettings}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType9;
        const $$createField32_0 = $$createType6;
        const $$createField33_0 = $$createType6;
        const $$createField34_0 = $$createType6;
        const $$createField35_0 = $$createType6;
        const $$createField36_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appCaptureProfiles" in $$parsedSource) {
            $$parsedSource["appCaptureProfiles"] = $$createField5_0($$parsedSource["appCaptureProfiles"]);
        }
        if ("excludeApps" in $$parsedSource) {
            $$parsedSource["excludeApps"] = $$createField32_0($$parsedSource["excludeApps"]);
        }
        if ("excludeWindowKeywords" in $$parsedSource) {
            $$parsedSource["excludeWindowKeywords"] = $$createField33_0($$parsedSource["excludeWindowKeywords"]);
        }
        if ("excludePaths" in $$parsedSource) {
            $$parsedSource["excludePaths"] = $$createField34_0($$parsedSource["excludePaths"]);
        }
        if ("excludeUrls" in $$parsedSource) {
            $$parsedSource["excludeUrls"] = $$createField35_0($$parsedSource["excludeUrls"]);
        }
        if ("excludeContentPatterns" in $$parsedSource) {
            $$parsedSource["excludeContentPatterns"] = $$createField36_0($$parsedSource["excludeContentPatterns"]);
        }
        return new WorkMemorySettings(/** @type {Partial<WorkMemorySettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GeneralSettings.createFrom;
const $$createType1 = Hotkeys.createFrom;
const $$createType2 = ScreenshotSettings.createFrom;
const $$createType3 = WorkMemorySettings.createFrom;
const $$createType4 = AISettings.createFrom;
const $$createType5 = PluginSettings.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = WorkMemoryAppCaptureProfile.createFrom;
const $$createType9 = $Create.Array($$createType8);
