// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class OpenResult {
    /**
     * Creates a new OpenResult instance.
     * @param {Partial<OpenResult>} [$$source = {}] - The source object to create the OpenResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pinId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenResult(/** @type {Partial<OpenResult>} */($$parsedSource));
    }
}

export class PinnedImage {
    /**
     * Creates a new PinnedImage instance.
     * @param {Partial<PinnedImage>} [$$source = {}] - The source object to create the PinnedImage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sourceId"] = undefined;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["imagePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["text"] = undefined;
        }
        if (!("dataUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataUrl"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("windowWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["windowX"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["windowY"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["positioned"] = undefined;
        }
        if (!("canCopy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canCopy"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["copyAction"] = undefined;
        }
        if (!("canOcr" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canOcr"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PinnedImage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PinnedImage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PinnedImage(/** @type {Partial<PinnedImage>} */($$parsedSource));
    }
}
