// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function Attach(app) {
    return $Call.ByID(535433101, app);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function ClosePinned(id) {
    return $Call.ByID(2743609646, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.PinnedImage>}
 */
export function GetPinned(id) {
    return $Call.ByID(1715593942, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {number} deltaX
 * @param {number} deltaY
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function MovePinned(id, deltaX, deltaY) {
    return $Call.ByID(8096927, id, deltaX, deltaY).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function OpenCapture(id) {
    return $Call.ByID(3114268242, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function OpenCaptureAt(id, x, y) {
    return $Call.ByID(3490087975, id, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function OpenClipboardImage(id) {
    return $Call.ByID(1824593571, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function OpenCurrentClipboard() {
    return $Call.ByID(3771305377).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function OpenQRText(text) {
    return $Call.ByID(718035220, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<$models.OpenResult>}
 */
export function SetPinnedPosition(id, x, y) {
    return $Call.ByID(1639077909, id, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OpenResult.createFrom;
const $$createType1 = $models.PinnedImage.createFrom;
